In [2]:
import numpy as np
import pandas as pd


from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import SGDClassifier

In [3]:
df = pd.read_csv('task_b.csv')


In [14]:
df.head()


index           f1            f2        f3    y
0      0  -195.871045 -14843.084171  5.532140  1.0
1      1 -1217.183964  -4068.124621  4.416082  1.0
2      2     9.138451   4413.412028  0.425317  0.0
3      3   363.824242  15474.760647  1.094119  0.0
4      4  -768.812047  -7963.932192  1.870536  0.0

In [15]:
X = df.drop(['y','index'],axis=1)
X

f1            f2        f3
0    -195.871045 -14843.084171  5.532140
1   -1217.183964  -4068.124621  4.416082
2       9.138451   4413.412028  0.425317
3     363.824242  15474.760647  1.094119
4    -768.812047  -7963.932192  1.870536
..           ...           ...       ...
195   119.423142  -2985.720392  0.929967
196   -37.805502  13061.298176  5.421253
197   181.626647   3179.754101  3.059868
198   443.199825  -1053.252455  5.467800
199   -51.189253   7442.423346  9.528478

[200 rows x 3 columns]

In [16]:
y = df[['y']]
y

y
0    1.0
1    1.0
2    0.0
3    0.0
4    0.0
..   ...
195  0.0
196  0.0
197  0.0
198  0.0
199  1.0

[200 rows x 1 columns]

In [17]:
df.std()

index       57.879185
f1         488.195035
f2       10403.417325
f3           2.926662
y            0.501255
dtype: float64

In [18]:
X=df[['f1','f2','f3']].values
Y=df['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


In [19]:
from sklearn.linear_model import LogisticRegression
model = SGDClassifier(loss='log',random_state=40)

In [38]:
Y=y.values.ravel()
Y

array([1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.])

In [45]:
model.fit(X,Y)

SGDClassifier(loss='log', random_state=40)

In [46]:
model.coef_

array([[ 6982.25676794, -2771.29956302, 11010.40779516]])

In [47]:
model.intercept_

array([95.06526399])

In [48]:
model2 = SGDClassifier(loss='hinge',random_state=40)

In [49]:
model2.fit(X,Y)

SGDClassifier(random_state=40)

In [50]:
model2.coef_

array([[ 9181.53524289, -3053.34987042, 10897.41941742]])

In [51]:
model2.intercept_

array([75.11588291])

In [ ]:
from the above results we can see that f3>f1>f2 without standardisation  ,so f3 is the most important feature  

In [52]:
df1 = StandardScaler().fit_transform(df[['f1','f2','f3']])

In [71]:
model3 = SGDClassifier(loss='log',random_state=20)
model3.fit(df1,Y)

SGDClassifier(loss='log', random_state=20)

In [72]:
model3.coef_

array([[-4.39481436,  3.26080903, 19.34567269]])

In [73]:
model3.intercept_

array([2.4638007])

In [74]:
model4 = SGDClassifier(loss='hinge',random_state=20)
model4.fit(df1,Y)

SGDClassifier(random_state=20)

In [75]:
model4.coef_


array([[-4.99641412,  1.89174837, 25.61846407]])

In [59]:
model4.intercept_

array([-0.61682405])

from the above rwesults we can see that f3>f1>f2 after standardisation ,so f3 is the most important feature  

# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>